[build]
  command = "yarn build"
  publish = ".next"
  
[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment variables can also be set in Netlify UI
[context.production.environment]
  NODE_ENV = "production"
